name: Building compiler

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ kawaii ]

jobs:
  build-windows:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run Npm
      run: |
        npm clean-install

    - name: Build Hexa
      run: |
        node bootstrap.js hexa.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hexa-node.js
        path: hexa-node.js
