name: Building compiler

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ kawaii ]

jobs:
  build-all:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2019, windows-2022, ubuntu-20.04, macos-11 ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run Npm
      run: |
        npm clean-install

    - name: Build Hexa
      run: |
        node --trace-uncaught bootstrap.js --define debug=false hexa.json
        node --trace-uncaught hexa-node.js --define debug=true --define times=false hexa.json
        node --trace-uncaught hexa-node.js --define debug=false --define times=false hexa.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hexa-node.js
        path: hexa-node.js
