name: Building tools

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ kawaii ]

jobs:
  build-windows:
    runs-on: windows-2019

    strategy:
      matrix:
        architecture:
          - amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: ${{ matrix.architecture }}

      - name: Build Library Generator
        run: |
          cl tools\libgen\main.cpp /Felibgen.exe /Os /INCREMENTAL:NO /nologo

      - name: Upload Library Generator
        uses: actions/upload-artifact@v3
        with:
          name: libgen
          path: libgen.exe
