name: Testing samples

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ kawaii ]

jobs:
  test-all:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2019, windows-2022, ubuntu-20.04, macos-11 ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Hexa
      uses: actions/download-artifact@v3
      with:
        name: hexa-node.js-${{ matrix.os }}
        path: hexa-node.js

    - name: Build tests
      run: |
        node --trace-uncaught hexa-node.js test/lts/hello/hexa.json
        node --trace-uncaught hexa-node.js test/normalizer/hexa.json

    - name: Build examples
      run: |
        node --trace-uncaught hexa-node.js examples/html-raytracer/hexa.json
        node --trace-uncaught hexa-node.js examples/native-posix/hexa.json
        node --trace-uncaught hexa-node.js examples/native-win32/hexa.json
        node --trace-uncaught hexa-node.js examples/node-platform/hexa.json
